### ISSUE TITLE
Ende eines Lides wird nicht gespeichert

### ISSUE THREAD

**Issue by tausday** [TobitSoftware/clipinc#6]
Hallo,

funktioniert clipinc derzeit?
Ich kann auf Record drücken, es erscheint auch "Aufnahme läuft", der Grüne Fortschrittsbalken vom Lied geht auch immer weiter.
Am Ende des Liedes bleibt der Balken bei 100% das nächste lied fängt an jedoch bleibt clipnic beim alten lied stehen und speichert auch nichts ab.

Vielen Dank

**Comment by huese23** [comment]
Hallo,

der Fehler wurde mit der Version 1.12.0 behoben. 

Viele Grüße
